onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /nf10_upb_interconnect_tb/gsr_r
add wave -noupdate /nf10_upb_interconnect_tb/gts_r
add wave -noupdate /nf10_upb_interconnect_tb/reset_i
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_1_n_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_2_n_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_1_p_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_2_p_r
add wave -noupdate /nf10_upb_interconnect_tb/axi_aclk
add wave -noupdate /nf10_upb_interconnect_tb/axi_resetn
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tdata
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tkeep
add wave -noupdate -radix unsigned /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tlast
add wave -noupdate /nf10_upb_interconnect_tb/RESET
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tready
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tready
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tdata
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tkeep
add wave -noupdate -radix unsigned /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tlast
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tdata
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tkeep
add wave -noupdate -radix unsigned /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tlast
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_clk1
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tready
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tdata
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tkeep
add wave -noupdate -radix unsigned /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tlast
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_clk2
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tready
add wave -noupdate /nf10_upb_interconnect_tb/rxp_1_i
add wave -noupdate /nf10_upb_interconnect_tb/rxn_1_i
add wave -noupdate /nf10_upb_interconnect_tb/txp_1_i
add wave -noupdate /nf10_upb_interconnect_tb/txn_1_i
add wave -noupdate /nf10_upb_interconnect_tb/rxp_2_i
add wave -noupdate /nf10_upb_interconnect_tb/rxn_2_i
add wave -noupdate /nf10_upb_interconnect_tb/txp_2_i
add wave -noupdate /nf10_upb_interconnect_tb/txn_2_i
add wave -noupdate /nf10_upb_interconnect_tb/rxp_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxn_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txp_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txn_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxp_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxn_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txp_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txn_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/error_count1
add wave -noupdate /nf10_upb_interconnect_tb/error_count2
add wave -noupdate /glbl/GSR
add wave -noupdate /nf10_upb_interconnect_tb/gsr_r
add wave -noupdate /nf10_upb_interconnect_tb/gts_r
add wave -noupdate /nf10_upb_interconnect_tb/reset_i
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_1_n_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_2_n_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_1_p_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_2_p_r
add wave -noupdate /nf10_upb_interconnect_tb/axi_aclk
add wave -noupdate /nf10_upb_interconnect_tb/axi_resetn
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tdata
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tlast
add wave -noupdate /nf10_upb_interconnect_tb/RESET
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tready
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tready
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tdata
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tlast
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tdata
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tlast
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_clk1
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tready
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tdata
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tlast
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_clk2
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tready
add wave -noupdate /nf10_upb_interconnect_tb/rxp_1_i
add wave -noupdate /nf10_upb_interconnect_tb/rxn_1_i
add wave -noupdate /nf10_upb_interconnect_tb/txp_1_i
add wave -noupdate /nf10_upb_interconnect_tb/txn_1_i
add wave -noupdate /nf10_upb_interconnect_tb/rxp_2_i
add wave -noupdate /nf10_upb_interconnect_tb/rxn_2_i
add wave -noupdate /nf10_upb_interconnect_tb/txp_2_i
add wave -noupdate /nf10_upb_interconnect_tb/txn_2_i
add wave -noupdate /nf10_upb_interconnect_tb/rxp_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxn_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txp_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txn_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxp_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxn_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txp_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txn_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/error_count1
add wave -noupdate /nf10_upb_interconnect_tb/error_count2
add wave -noupdate /glbl/GSR
add wave -noupdate /nf10_upb_interconnect_tb/gsr_r
add wave -noupdate /nf10_upb_interconnect_tb/gts_r
add wave -noupdate /nf10_upb_interconnect_tb/reset_i
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_1_n_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_2_n_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_1_p_r
add wave -noupdate /nf10_upb_interconnect_tb/reference_clk_2_p_r
add wave -noupdate /nf10_upb_interconnect_tb/axi_aclk
add wave -noupdate /nf10_upb_interconnect_tb/axi_resetn
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tdata
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tlast
add wave -noupdate /nf10_upb_interconnect_tb/RESET
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tready
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tready
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tdata
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tlast
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tdata
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis1_tlast
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_clk1
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis1_tready
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tdata
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/arbiter_m_axis2_tlast
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_clk2
add wave -noupdate /nf10_upb_interconnect_tb/output_queue_s_axis2_tready
add wave -noupdate /nf10_upb_interconnect_tb/rxp_1_i
add wave -noupdate /nf10_upb_interconnect_tb/rxn_1_i
add wave -noupdate /nf10_upb_interconnect_tb/txp_1_i
add wave -noupdate /nf10_upb_interconnect_tb/txn_1_i
add wave -noupdate /nf10_upb_interconnect_tb/rxp_2_i
add wave -noupdate /nf10_upb_interconnect_tb/rxn_2_i
add wave -noupdate /nf10_upb_interconnect_tb/txp_2_i
add wave -noupdate /nf10_upb_interconnect_tb/txn_2_i
add wave -noupdate /nf10_upb_interconnect_tb/rxp_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxn_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txp_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txn_1_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxp_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/rxn_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txp_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/txn_2_i_error
add wave -noupdate /nf10_upb_interconnect_tb/error_count1
add wave -noupdate /nf10_upb_interconnect_tb/error_count2
add wave -noupdate /glbl/GSR
add wave -noupdate -divider -height 40 interconnect1
add wave -noupdate /nf10_upb_interconnect_tb/uut1/C_PORT_NUMBER
add wave -noupdate /nf10_upb_interconnect_tb/uut1/C_INPORT_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut1/C_OUTPORT_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut1/C_PACKET_LENGTH_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut1/C_MAX_PACKET_LENGTH
add wave -noupdate /nf10_upb_interconnect_tb/uut1/C_AXIS_DATA_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut1/SIM_GTXRESET_SPEEDUP
add wave -noupdate /nf10_upb_interconnect_tb/uut1/AXIS_DATA_WIDTH_BYTE
add wave -noupdate /nf10_upb_interconnect_tb/uut1/axi_aclk
add wave -noupdate /nf10_upb_interconnect_tb/uut1/axi_resetn
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tready
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_clk
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tready
add wave -noupdate /nf10_upb_interconnect_tb/uut1/output_queue_s_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut1/RESET
add wave -noupdate /nf10_upb_interconnect_tb/uut1/INIT_CLK
add wave -noupdate /nf10_upb_interconnect_tb/uut1/GT_RESET_IN
add wave -noupdate /nf10_upb_interconnect_tb/uut1/GTXD8_P
add wave -noupdate /nf10_upb_interconnect_tb/uut1/GTXD8_N
add wave -noupdate /nf10_upb_interconnect_tb/uut1/RXP
add wave -noupdate /nf10_upb_interconnect_tb/uut1/RXN
add wave -noupdate /nf10_upb_interconnect_tb/uut1/TXP
add wave -noupdate /nf10_upb_interconnect_tb/uut1/TXN
add wave -noupdate /nf10_upb_interconnect_tb/uut1/axi_reset
add wave -noupdate /nf10_upb_interconnect_tb/uut1/clk
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_below_low
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_above_high
add wave -noupdate /nf10_upb_interconnect_tb/uut1/flow_control_pause_req
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_data
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_keep
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_pkt_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_last
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_error
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_keep_enc
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_dip
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_almost_emtpy
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_almost_full
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_empty
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_full
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_dop
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_error
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_pkt_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_last
add wave -noupdate /nf10_upb_interconnect_tb/uut1/wide_fifo_keep_enc
add wave -noupdate /nf10_upb_interconnect_tb/uut1/dropping
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pkt_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/next_pkt_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/length_check_ok
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_full
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_empty
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_eop
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_commit
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_revert
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_wren
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_mi
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_di
add wave -noupdate /nf10_upb_interconnect_tb/uut1/pa_fifo_mo
add wave -noupdate /nf10_upb_interconnect_tb/uut1/arbiter_m_axis_tkeep_enc
add wave -noupdate -divider -height 40 aurora_input1
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/C_PACKET_LENGTH_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/C_AXIS_DATA_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/SIM_GTXRESET_SPEEDUP
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/AXIS_DATA_WIDTH_BYTE
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/TX_DELAY_CYCLES
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/RX_DELAY_CYCLES
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/axi_resetn
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/m_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/m_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/m_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/m_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/m_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/error
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/clk156
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/s_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/s_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/s_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/s_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/s_axis_tready
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/s_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/flow_control_pause_req
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/flow_control_pause_val
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/RESET
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/INIT_CLK
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/GT_RESET_IN
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/GTXD8_P
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/GTXD8_N
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/RXP
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/RXN
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/TXP
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/TXN
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/axi_reset
add wave -noupdate -radix hexadecimal /nf10_upb_interconnect_tb/uut1/aurora_input/tx_d_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_src_rdy_n_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_dst_rdy_n_i
add wave -noupdate -radix hexadecimal /nf10_upb_interconnect_tb/uut1/aurora_input/rx_d_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_src_rdy_n_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/GTXD8_left_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/hard_err_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/soft_err_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/channel_up_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/lane_up_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/warn_cc_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/do_cc_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/pll_not_locked_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/user_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/sync_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/reset_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/power_down_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/loopback_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_lock_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_lock_out_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_out_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/buf_tx_out_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/gt_reset_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/system_reset_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/err_count_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/icon_to_vio_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/sync_in_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/sync_out_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/lane_up_i_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_lock_i_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/lane_up_reduce_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rst_cc_module_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tied_to_gnd_vec_i
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_data
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_stopped
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/flow_control_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_data_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_control_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_crc_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/s_axis_tkeep_enc
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_crc
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_control_lane
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/tx_d_i_reverse
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/fetch_s_axis_data
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/to_send_data_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/to_send_flow_ctrl_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_data_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_control_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_crc_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_crc_calc_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_src_rdy_n_i_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_crc
add wave -noupdate /nf10_upb_interconnect_tb/uut1/aurora_input/rx_d_i_reverse
add wave -noupdate -divider -height 40 interconnect2
add wave -noupdate /nf10_upb_interconnect_tb/uut2/C_PORT_NUMBER
add wave -noupdate /nf10_upb_interconnect_tb/uut2/C_INPORT_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut2/C_OUTPORT_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut2/C_PACKET_LENGTH_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut2/C_MAX_PACKET_LENGTH
add wave -noupdate /nf10_upb_interconnect_tb/uut2/C_AXIS_DATA_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut2/SIM_GTXRESET_SPEEDUP
add wave -noupdate /nf10_upb_interconnect_tb/uut2/AXIS_DATA_WIDTH_BYTE
add wave -noupdate /nf10_upb_interconnect_tb/uut2/axi_aclk
add wave -noupdate /nf10_upb_interconnect_tb/uut2/axi_resetn
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tready
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_clk
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tuser_in_port
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tuser_out_port
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tuser_in_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tuser_out_vport
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tready
add wave -noupdate /nf10_upb_interconnect_tb/uut2/output_queue_s_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut2/RESET
add wave -noupdate /nf10_upb_interconnect_tb/uut2/INIT_CLK
add wave -noupdate /nf10_upb_interconnect_tb/uut2/GT_RESET_IN
add wave -noupdate /nf10_upb_interconnect_tb/uut2/GTXD8_P
add wave -noupdate /nf10_upb_interconnect_tb/uut2/GTXD8_N
add wave -noupdate /nf10_upb_interconnect_tb/uut2/RXP
add wave -noupdate /nf10_upb_interconnect_tb/uut2/RXN
add wave -noupdate /nf10_upb_interconnect_tb/uut2/TXP
add wave -noupdate /nf10_upb_interconnect_tb/uut2/TXN
add wave -noupdate /nf10_upb_interconnect_tb/uut2/axi_reset
add wave -noupdate /nf10_upb_interconnect_tb/uut2/clk
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_below_low
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_above_high
add wave -noupdate /nf10_upb_interconnect_tb/uut2/flow_control_pause_req
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_data
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_keep
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_pkt_length
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_last
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_error
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_keep_enc
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_dip
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_almost_emtpy
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_almost_full
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_empty
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_full
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_dop
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_error
add wave -noupdate -radix unsigned /nf10_upb_interconnect_tb/uut2/wide_fifo_pkt_length
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_last
add wave -noupdate /nf10_upb_interconnect_tb/uut2/wide_fifo_keep_enc
add wave -noupdate /nf10_upb_interconnect_tb/uut2/dropping
add wave -noupdate -radix unsigned /nf10_upb_interconnect_tb/uut2/pkt_length
add wave -noupdate -radix unsigned /nf10_upb_interconnect_tb/uut2/next_pkt_length
add wave -noupdate /nf10_upb_interconnect_tb/uut2/length_check_ok
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_full
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_empty
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_eop
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_commit
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_revert
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_wren
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_mi
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_di
add wave -noupdate /nf10_upb_interconnect_tb/uut2/pa_fifo_mo
add wave -noupdate /nf10_upb_interconnect_tb/uut2/arbiter_m_axis_tkeep_enc
add wave -noupdate -divider -height 40 aurora_input2
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/C_PACKET_LENGTH_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/C_AXIS_DATA_WIDTH
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/SIM_GTXRESET_SPEEDUP
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/AXIS_DATA_WIDTH_BYTE
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/TX_DELAY_CYCLES
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/RX_DELAY_CYCLES
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/axi_resetn
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/m_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/m_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/m_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/m_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/m_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/error
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/clk156
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/s_axis_tdata
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/s_axis_tkeep
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/s_axis_tuser_packet_length
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/s_axis_tvalid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/s_axis_tready
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/s_axis_tlast
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/flow_control_pause_req
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/flow_control_pause_val
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/RESET
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/INIT_CLK
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/GT_RESET_IN
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/GTXD8_P
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/GTXD8_N
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/RXP
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/RXN
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/TXP
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/TXN
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/axi_reset
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_d_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_src_rdy_n_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_dst_rdy_n_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_d_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_src_rdy_n_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/GTXD8_left_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/hard_err_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/soft_err_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/channel_up_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/lane_up_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/warn_cc_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/do_cc_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/pll_not_locked_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/user_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/sync_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/reset_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/power_down_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/loopback_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_lock_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_lock_out_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_out_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/buf_tx_out_clk_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/gt_reset_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/system_reset_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/err_count_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/icon_to_vio_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/sync_in_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/sync_out_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/lane_up_i_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_lock_i_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/lane_up_reduce_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rst_cc_module_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tied_to_gnd_vec_i
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_data
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_stopped
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/flow_control_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_data_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_control_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_crc_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/s_axis_tkeep_enc
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_crc
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_control_lane
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/tx_d_i_reverse
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/fetch_s_axis_data
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/to_send_data_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/to_send_flow_ctrl_valid
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_data_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_control_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_crc_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_crc_calc_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_src_rdy_n_i_delayed
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_crc
add wave -noupdate /nf10_upb_interconnect_tb/uut2/aurora_input/rx_d_i_reverse
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3695050 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 376
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {3588210 ps} {3775091 ps}
bookmark add wave bookmark0 {{14135156 ps} {14486743 ps}} 263
